### ISSUE TITLE
大佬，能不能把所有的api接口都完善一下，谢谢

### ISSUE THREAD

**Issue by banzuan** [speauty/SFQiao#1]

**Comment by speauty** [comment]
除了下单和物流的两个回调, 其他都已经对接了哦

**Comment by banzuan** [comment]
> 除了下单和物流的两个回调, 其他都已经对接了哦

打印面单的接口没有对接吧？

**Comment by ben5473** [comment]
大佬，更新下 guzzlehttp/guzzle 版本吧

**Comment by banzuan** [comment]
什么api接口



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 下午3:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [speauty/SFQiao] 大佬，能不能把所有的api接口都完善一下，谢谢 (#1)





 
大佬，更新下 guzzlehttp/guzzle 版本吧
